name: Build index.html

on:
  push:
    branches:
      - main  # or replace with the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate index.html
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html>" >> index.html
          echo "<body>" >> index.html
          echo "<h1>Directory of HTML Files</h1>" >> index.html
          echo "<ul>" >> index.html
          find . -name '*.html' -not -name 'index.html' | while read -r file; do
            echo "<li><a href='${file#./}'>${file#./}</a></li>" >> index.html
          done
          echo "</ul>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Automatically update index.html" -a || true  # Don't fail if there's nothing to commit
          git push
